//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public int Id { get; set; }
        public int IdProyecto { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
